$# LS-DYNA Keyword file created by LS-PrePost(R) V4.3 (Beta) - 20Dec2015(08:00)
$# Created on Mar-17-2017 (10:07:19)
*KEYWORD  
*TITLE
$#                                                                         title
LS-DYNA keyword deck by LS-PrePost
*ELEMENT_SHELL
$#   eid     pid      n1      n2      n3      n4      n5      n6      n7      n8
  1	 100 4	1	5 5
  2  100 1	2	5 5
  3	 100 5	2	3 3
  4	 100 5	3	6 6
*NODE
$#   nid               x               y               z      tc      rc 
1	0.120	-0.050	0.050
2	0.120	0.0	0.050
3 	0.120	0.050	0.050
4	0.060	-0.050	0.040
5	0.060	0.0	0.040
6	0.060	0.050	0.040
*END
